---
title: "Biology 207 Tutorial"
output: html_document
---


```{r Importing and Looking at the Data}
library(readxl)
Biol207TutorialDataset <- read_excel("Biol207TutorialDataset.xlsx")
View(Biol207TutorialDataset)
summary(Biol207TutorialDataset)
```

```{r install and load packages}

if (!require("ggplot2")) install.packages("ggplot2", repos='http://cran.us.r-project.org')
if (!require("cowplot")) install.packages("cowplot", repos='http://cran.us.r-project.org')
if (!require("UsingR")) install.packages("UsingR", repos='http://cran.us.r-project.org')
library(ggplot2)
library(cowplot)
library(UsingR)
```


```{r explore data}
simple.eda(Biol207TutorialDataset$`Fiber length (cm)`)
shapiro.test(Biol207TutorialDataset$`Fiber length (cm)`)
simple.eda(Biol207TutorialDataset$`Fleece weight (kg)`)
shapiro.test(Biol207TutorialDataset$`Fleece weight (kg)`)
```



```{r create scatterplot}
ggplot(Biol207TutorialDataset) +
  aes(x = as.numeric(Biol207TutorialDataset$`Fiber length (cm)`), y = Biol207TutorialDataset$`Fleece weight (kg)`) +
  geom_point() +
  geom_smooth(method='lm',color="black", se=TRUE) +
  theme_cowplot() +
  xlab("Fiber Length (cm)") + 
  ylab("Fleece Weight (kg)")
```

```{r find correlation coefficient}
fit = lm(Biol207TutorialDataset$`Fleece weight (kg)`~Biol207TutorialDataset$`Fiber length (cm)`, data=Biol207TutorialDataset)
summary(fit)
```
